### ISSUE TITLE
Demo page 404 error

### ISSUE THREAD

**Issue by Chrisp-hp** [grbsk/ng2-idle#215]
the demo https://moribvndvs.github.io/ng2-idle to view a an example with quick start instructions is not avaleable, getting 404 not found error.

![image](https://github.com/user-attachments/assets/76feb5f5-3cdb-4a68-b741-510aaaf2ce71)

**Comment by grbsk** [comment]
I needed to rename my GitHub account. The readme link was out of date but has been updated, but the link in the information section of the repo was already correct.
